name: Pull Request Creator
on:
  push:
    branches: ['test-branch']

jobs:
  pull-request:
    environment: workflow_environment
    name: Open PR
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "${{ secrets.DESTINATION_BRANCH }}"
        pr_title: "Automated Pull Request: Pulling ${{ github.ref_name }} into ${{ secrets.DESTINATION_BRANCH }}"
        pr_reviewer: "${{ secrets.REVIEWERS }}"
        pr_label: "auto-pr"
        github_token: ${{ secrets.GITHUB_TOKEN }}
